name = "fedora"
description = "Fedora rawhide from GitHub Actions"
version = "0.0.2"
modules = []
groups = []

[[packages]]
name = "awscli"
version = "*"

[[packages]]
name = "fedora-packager"
version = "*"

[[packages]]
name = "tmux"
version = "*"

[[packages]]
name = "tuned"
version = "*"

[customizations.services]
enabled = ["tuned"]
