name: CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Retrieve the previously built container (if it exists)
        run: docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} || true

      - name: Build Image Builder container
        run: |
          docker build \
            -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest \
            -f Dockerfile \
            --cache-from=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} \
            .

      - name: Push the container
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      - name: Fill in the AWS template
        run: |
          cat shared/aws-template.toml | envsubst > shared/aws-config.toml
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_BUCKET: major-aws-image-import
          AWS_DEFAULT_REGION: us-east-1

      - name: Run the build
        run: ./build-image.sh
